# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MakeApiCallApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MakeApiCallApp
    pod 'Alamofire'
    pod 'SwiftSpinner'
    pod 'SwiftyJSON', '~> 4.0'
end
